export const FETCH_FURNITURE_DATA_START = 'FETCH_FURNITURE_DATA_START';
export const FETCH_FURNITURE_DATA_SUCCESS = 'FETCH_FURNITURE_DATA_SUCCESS';
export const FETCH_FURNITURE_DATA_FAILURE = 'FETCH_FURNITURE_DATA_FAILURE';
